# Generated by Django 4.0.6 on 2022-08-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_remove_course_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='state',
            field=models.TextField(default='A', max_length=1),
        ),
    ]
